name: Release
on:
  workflow_dispatch:
    branches:
      - main
permissions: {}
jobs:
  release:
    permissions:
      contents: write # to create release (changesets/action)
      pull-requests: write # to create pull request (changesets/action)

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          key: node_modules-${{ hashFiles('package.json') }}-${{ hashFiles('package-lock.json') }}
          path: '**/node_modules'

      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Create Release Pull Request
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
